### ISSUE TITLE
Protocol check when encoding as well as when decoding

### ISSUE THREAD

**Issue by joker314** [redirectatob/redirectatob.github.io#20]
To prevent someone defaming the author of this website, schemes at the starts of URLs which are able run code in the context of redirectatob are disallowed. This includes the `javascript` scheme. (see #2).

When a user tries to encode a disallowed scheme -- they are not warned that such an act is illegal. A URL is presented to them -- and if they don't test it, they may assume everything is okay, and even give it to their friends.

When the redirectatob is opened, however, "Invalid protocol specified" is shown.

Therefore, _in addition to_ validating the URL when redirecting; we should also validate when encoding.

<hr>

An alternative to this is to carefully open the presented URL in a new tab, and allow any schema. Then, once it's opened, we close redirectatob. This way, any JavaScript code will have a URL of `javascript:...` rather than `redirectatob.github.io/#...`. Thoughts?

**Comment by joker314** [comment]
Opera is the only browser to not support the `pattern` attribute on inputs. Otherwise, it could be a JavaScript-free way of enforcing validation. (Click image below for source)

I propose a hybrid of JS and `validation`-attribute? The former would only trigger on Opera.

[![Browser Compatibility table](https://user-images.githubusercontent.com/18113170/45601797-bf7ed600-ba0a-11e8-9748-57486357af82.png)](https://caniuse.com/#feat=input-pattern)

**Comment by towerofnix** [comment]
> I propose a hybrid of JS and pattern-attribute? The former would only trigger on Opera.

I'm inclined against a hybrid solution.. well, usually. Since it's only really one line of code ([this one](https://github.com/redirectatob/redirectatob.github.io/blob/f6f6f48f195c771df5ad0da529a435610543472b/index.html#L33)), it's probably fine to use both JS and `pattern` here. (But don't explicitly check if the browser is Opera.)

> An alternative to this is to carefully open the presented URL in a new tab, and allow any schema. Then, once it's opened, we close redirectatob.

I see what you mean, and maybe it's practical (e.g. you could link to `ftp://` URLs), but I'm not entirely convinced. For one, if popup windows/tabs are disabled (and 99% of the time they are), would this still work?
