### ISSUE TITLE
Add a background image.

### ISSUE THREAD

**Issue by ktrvs** [redirectatob/redirectatob.github.io#5]
It would maybe be quite a nice addition to add a background image to the site instead of the white background.

**Comment by ktrvs** [comment]
A couple of free use images that are really nice are:

![Uploading hugo-kemmel-289805.jpg…]()
![amy-hanley-97656](https://user-images.githubusercontent.com/26391179/36098157-c2ce5be2-0ff5-11e8-89e1-a3b943fe1e4d.jpg)

Obviously, it would be a good idea to compress them first.

**Comment by joker314** [comment]
I can confirm the above image is in the Public Domain. However, it's not really relevant to redirecting. Nonetheless, it's visually appealing so, maybe, _shrugs_.

**Comment by ktrvs** [comment]
> it's visually appealing so, maybe, shrugs.

That's what I had in mind. As a designer, I always think that every tool should look good, no matter what the purpose of it is.

**Comment by towerofnix** [comment]
As a not-designer, I don't think the backdrop needs to be an *image*. The only way for a background image to look good is for it to be high-resolution, and high-res images are costly for cell phones and such.

The background color of make.html is white, and this [is intentional](https://github.com/redirectatob/redirectatob.github.io/blob/c770405b51aa58bab99ea14546672b79f6f8cc1c/make.css#L9). I tried some other colors and they simply didn't look as nice. (If you *do* find a color that seems particularly appealing - make sure you're trying with inspect element! - then please tell me, I might use it.)

On the other hand I think there are a few other things which are more important than a background image, like fixing the link text overflow and fixing the input style. This screenshot shows both issues:

![Link flows outside of blue content box; input box is inset and has no background](https://user-images.githubusercontent.com/9948030/36103896-f0eaf3fa-0fe6-11e8-9c9a-eba901d68153.png)

**Comment by ktrvs** [comment]
Well, I messed about and got this:

![1](https://user-images.githubusercontent.com/26391179/36104334-9af0f274-1009-11e8-9c70-51f5421a26d1.png)

Background - #2C3E50
Container - #19B5FE
Container Shadow - #2574A9

**Comment by towerofnix** [comment]
I like the dark theme but wonder if it's really appropraite in this case? Most websites are much more light-themed, especially social media sites, which are where redirectatob is actually useful.

**Comment by ktrvs** [comment]
Hmm, Well, it is up to you, of course.

**Comment by joker314** [comment]
Why not, then, swap the background with the container?

**Comment by towerofnix** [comment]
@joker314 That would make the text black on deep blue if you're talking about the dark theme. The light theme looks pretty good flipped, though:

![Container is white, backdrop is blue (same blue as current container fill)](https://user-images.githubusercontent.com/9948030/36104991-e25bf52a-0fe9-11e8-9dce-2385f45252f7.png)

**Comment by joker314** [comment]
Yeah, I like that! The input box could do with some internal padding (that's what it's called, right?); because the placeholder text is hugging the border really tightly

**Comment by ktrvs** [comment]
Oooh, Nice!

> The input box could do with some internal padding (that's what it's called, right?); because the placeholder text is hugging the border really tightly

Yeah.
